config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: %w(cat dog racoon muskrat snake dragon cerbère bat)}
  validates :age, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :owner, :age, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/edit.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :owner %>
  <%= f.input :species %>
  <%= f.input :age %>
  <%= f.button :submit %>
<% end %>

app/views/pets/index.html.erb
<div class="banner d-flex justify-content-center">
  <div >
    Welcome
  </div>
</div>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <%= link_to pet.name, pet_path(pet) %>
    </li>
  <% end %>
</ul>

<%= link_to 'create', new_pet_path %>

app/views/pets/new.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :owner %>
  <%= f.input :species %>
  <%= f.input :age %>
  <%= f.button :submit %>
<% end %>

app/views/pets/show.html.erb
<div class="banner d-flex justify-content-center">
  <div >
    Welcome
  </div>
</div>

<%= link_to '<- retour', pets_path %>

<h1><%= @pet.name %> by <%= @pet.owner %></h1>

<h2><%= @pet.species %></h2>

<h3><%= @pet.age %></h3>

<%= link_to 'edit', edit_pet_path(@pet) %>
<%= link_to 'delete', pet_path(@pet), method: :delete %>